#!/usr/bin/env node

var Orchestrator =	require('orchestrator');





var tasks = new Orchestrator();
var data = {
	stations:	{},
	agencies:	{},
	routes:		{}
};



var download =		require('../util/download');
tasks.add('download', function () {
	return Q.all([
		download('stops.txt'),
		download('stop_times.txt'),
		download('agency.txt'),
		download('routes.txt')
	]);
});



var stations =		require('./stations');
tasks.add('stations', ['download'], function () {
	return stations.parse(data.stations)
	.then(stations.weights)
	.then(stations.save);
});



var agencies =		require('./agencies');
tasks.add('agencies', ['download'], function () {
	return agencies.parse(data.agencies)
	.then(agencies.save);
});



var routes =		require('./routes');
tasks.add('routes', ['download'], function () {
	return routes.parse(data.routes)
	.then(routes.save);
});



var remove =		require('../util/remove');
tasks.add('all', ['stations', 'agencies', 'routes'], function () {
	return Q.all([
		remove('stops.txt'),
		remove('stop_times.txt'),
		remove('agency.txt'),
		remove('routes.txt')
	]);
});





tasks.start('all');
